# Generated by Django 3.0.6 on 2020-05-15 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajayiezekiel9000scrumy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goalstatus',
            name='status_name',
            field=models.CharField(max_length=150),
        ),
    ]
